obj_stim = ['8ball.jpg','aceofdiamond.jpg', 'aloe01.jpg', 'apple05b.jpg', 'apron.jpg', 'armchair02.jpg',
'axe02.jpg', 'badmintonracket.jpg', 'ballofstring.jpg', 'balloon01a.jpg',
'banana04a.jpg', 'barbecue03.jpg', 'basketball01.jpg', 'bed.jpg', 'beerbottle.jpg',
'belt03b.jpg', 'bicycle.jpg', 'birthdaycandle.jpg', 'blueberry02.jpg', 'bluecheese.jpg', 'bookshelf.jpg', 
'bottleofwhitewine.jpg', 'bowlingpin.jpg', 'bowlofcereal.jpg', 'bowtie.jpg', 'boxtruck.jpg', 'broccoli01b.jpg', 
'broom02.jpg', 'cactus.jpg', 'calculator02c.jpg', 'candelabra.jpg', 'candycane01a.jpg', 'canoftennisballs.jpg', 
'cap01b.jpg', 'chainsaw.jpg', 'chandelier.jpg', 'chisel01b.jpg',
'chocolatemilk.jpg', 'christmaslights.jpg', 'cleaver02.jpg', 'clothespin03a.jpg',
'computerkeyboard01a.jpg', 'corkscrew05.jpg', 'croissant02a.jpg',
'crown.jpg', 'curtain.jpg', 'daisy.jpg', 'dartboard.jpg', 'dice02a.jpg', 'dolly01.jpg',
'dresser02.jpg', 'drill02a.jpg',
'dryingmachine01.jpg', 'exercisebike.jpg', 'eyepatch.jpg','fireextinguisher02.jpg', 
'firtree.jpg', 'fishingrod.jpg', 'flashlight05.jpg',
'flipflop01b.jpg', 'foosballtable.jpg', 'fork03b.jpg', 'frenchfries.jpg', 
'frisbee.jpg', 'fryingpan03.jpg', 'gamecontroller01.jpg', 'gardenshears01b.jpg', 
'garlic01b.jpg', 'glasses01b.jpg', 'golfball.jpg', 'grandpiano.jpg', 'grape02.jpg',
'hairdryer01a.jpg', 'handfan01a.jpg', 'handmixer01a.jpg', 'hanger05a.jpg',
'hardhat02.jpg','hat05.jpg', 'headphones02a.jpg', 'highheelshoe02a.jpg',
'highlighter04b.jpg','hotdog.jpg', 'hulahoop.jpg',
'icecreamcone02a.jpg', 'interlockingbuildingblock01.jpg', 'iron01a.jpg', 'jeans01.jpg', 'jeep.jpg', 'jetski.jpg',
'kite.jpg', 'kiwi03.jpg', 'lawnmower.jpg', 'leaf01a.jpg', 'lemon01.jpg',
'lifesaver.jpg', 'lightbulb02a.jpg',
'lighter02a.jpg', 'lilypad.jpg', 'lipstick01a.jpg', 'lock02b.jpg', 'locomotive.jpg', 'loppingshears.jpg',
'mailbox02.jpg', 'makiroll.jpg', 'maraca02a.jpg',
'mathcompass.jpg', 'megaphone.jpg', 'microwave.jpg', 'mitten02b.jpg', 'motorcycle.jpg', 
'muffin.jpg', 'mug05.jpg', 'mushroom02.jpg', 'musicstand.jpg', 'nailclipper05.jpg',
'nintendods.jpg',
'oven.jpg', 'paintroller02.jpg', 'paperclip04.jpg', 'parachute.jpg',
'parkbench02.jpg', 
'peach02.jpg', 'peanut02.jpg', 'pencilsharpener03b.jpg',
'pepper04b.jpg', 'phonebooth.jpg', 'pineapple01b.jpg', 'pingpongtable.jpg',
'pokerchips.jpg', 'poloshirt.jpg', 'potato01.jpg', 'pumpkin.jpg','rainboot.jpg', 
'razor02a.jpg', 'redonion.jpg', 'remotecontrol01a.jpg', 'rollerblade.jpg',
'rollingpin01b.jpg', 'rose.jpg', 'rubikcube.jpg',
'saltshaker03c.jpg', 'saxophone.jpg', 'scissors02a.jpg', 'scooter.jpg', 
'screwdriver01.jpg',
'shovel02.jpg', 'shower.jpg', 'sieve01a.jpg', 'sink.jpg', 'skateboard.jpg', 'skigoggles02a.jpg',
'smokingpipe.jpg', 'soccercleat02.jpg', 'sock02.jpg', 'spaghetti01.jpg', 
'sponge03a.jpg', 'spraybottle03.jpg', 'sprouts.jpg',
'stapler01.jpg', 'steeringwheel.jpg', 'stool01.jpg', 'stubbywrench01a.jpg', 'sunglasses06c.jpg',
'surfboard.jpg', 'tabascosauce.jpg', 'table01.jpg', 'thermometer03a.jpg', 'thumbtack02b.jpg',
'tie01.jpg', 'tissuebox01a.jpg', 'toaster02.jpg', 'toiletbrush.jpg', 
'tongs01a.jpg', 'toothbrush01.jpg', 'towel02a.jpg', 
'tractor.jpg', 'trampoline.jpg', 'tree.jpg', 'triangle.jpg',
'tricycle.jpg', 'trumpet.jpg', 'tuque03b.jpg', 'turnip.jpg', 'tweezers02b.jpg',
'umbrella02a.jpg', 
'vacuumcleaner01.jpg', 'volleyball.jpg', 'wallclock.jpg', 'walnut01b.jpg', 'watch03a.jpg', 
'waterlily.jpg', 'watermelon03.jpg',
'weddingcake.jpg', 'weight05a.jpg', 'wetfloorsign.jpg', 'wheelbarrow01.jpg', 'wheelchair.jpg',
'woodenshoe.jpg', 'zipper.jpg', 'zucchini02.jpg'];  

sc_stim = ['ballroom.jpg', 'lighthouse.jpg', 'sauna.jpg', 'wheat_field.jpg'];